-- MySQL Script generated by MySQL Workbench
-- Tue Nov 19 06:33:25 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cpsc332_db_project
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cpsc332_db_project` ;

-- -----------------------------------------------------
-- Schema cpsc332_db_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cpsc332_db_project` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
SHOW WARNINGS;
USE `cpsc332_db_project` ;

-- -----------------------------------------------------
-- Table `cpsc332_db_project`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cpsc332_db_project`.`person` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cpsc332_db_project`.`person` (
  `person_id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `street_address` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `zip` VARCHAR(45) NULL,
  `ssn` VARCHAR(45) NULL,
  PRIMARY KEY (`person_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `person_id_UNIQUE` ON `cpsc332_db_project`.`person` (`person_id` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cpsc332_db_project`.`doctor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cpsc332_db_project`.`doctor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cpsc332_db_project`.`doctor` (
  `doctor_id` VARCHAR(10) NOT NULL,
  `fk_person_id` INT NOT NULL,
  `medial_degree` VARCHAR(45) NULL,
  PRIMARY KEY (`doctor_id`),
  CONSTRAINT `fk_doctor_person1`
    FOREIGN KEY (`fk_person_id`)
    REFERENCES `cpsc332_db_project`.`person` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_doctor_person1_idx` ON `cpsc332_db_project`.`doctor` (`fk_person_id` ASC) ;

SHOW WARNINGS;
CREATE UNIQUE INDEX `doctor_id_UNIQUE` ON `cpsc332_db_project`.`doctor` (`doctor_id` ASC) ;

SHOW WARNINGS;
CREATE UNIQUE INDEX `fk_person_id_UNIQUE` ON `cpsc332_db_project`.`doctor` (`fk_person_id` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cpsc332_db_project`.`prescription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cpsc332_db_project`.`prescription` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cpsc332_db_project`.`prescription` (
  `prescription_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`prescription_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cpsc332_db_project`.`patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cpsc332_db_project`.`patient` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cpsc332_db_project`.`patient` (
  `patient_id` INT NOT NULL AUTO_INCREMENT,
  `fk_person_id` INT NOT NULL,
  `DOB` DATE NULL,
  PRIMARY KEY (`patient_id`),
  CONSTRAINT `fk_patient_person`
    FOREIGN KEY (`fk_person_id`)
    REFERENCES `cpsc332_db_project`.`person` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_patient_person1_idx` ON `cpsc332_db_project`.`patient` (`fk_person_id` ASC) ;

SHOW WARNINGS;
CREATE UNIQUE INDEX `fk_person_id_UNIQUE` ON `cpsc332_db_project`.`patient` (`fk_person_id` ASC) ;

SHOW WARNINGS;
CREATE UNIQUE INDEX `patient_id_UNIQUE` ON `cpsc332_db_project`.`patient` (`patient_id` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cpsc332_db_project`.`visit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cpsc332_db_project`.`visit` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cpsc332_db_project`.`visit` (
  `visit_id` INT NOT NULL,
  `fk_patient_id` INT NOT NULL,
  `fk_doctor_id` VARCHAR(10) NOT NULL,
  `date` DATETIME NOT NULL,
  `room` VARCHAR(45) NOT NULL,
  `doc_note` TEXT(256) NULL,
  PRIMARY KEY (`visit_id`),
  CONSTRAINT `fk_appointment_patient1`
    FOREIGN KEY (`fk_patient_id`)
    REFERENCES `cpsc332_db_project`.`patient` (`patient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appointment_doctor1`
    FOREIGN KEY (`fk_doctor_id`)
    REFERENCES `cpsc332_db_project`.`doctor` (`doctor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_appointment_doctor1_idx` ON `cpsc332_db_project`.`visit` (`fk_doctor_id` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cpsc332_db_project`.`test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cpsc332_db_project`.`test` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cpsc332_db_project`.`test` (
  `test_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`test_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cpsc332_db_project`.`specialty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cpsc332_db_project`.`specialty` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cpsc332_db_project`.`specialty` (
  `spec_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`spec_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `spec_id_UNIQUE` ON `cpsc332_db_project`.`specialty` (`spec_id` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cpsc332_db_project`.`doctor_specialty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cpsc332_db_project`.`doctor_specialty` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cpsc332_db_project`.`doctor_specialty` (
  `fk_doctor_id` VARCHAR(10) NOT NULL,
  `fk_spec_id` INT NOT NULL,
  PRIMARY KEY (`fk_doctor_id`, `fk_spec_id`),
  CONSTRAINT `fk_doctor_has_specialty_doctor1`
    FOREIGN KEY (`fk_doctor_id`)
    REFERENCES `cpsc332_db_project`.`doctor` (`doctor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doctor_has_specialty_specialty1`
    FOREIGN KEY (`fk_spec_id`)
    REFERENCES `cpsc332_db_project`.`specialty` (`spec_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_doctor_has_specialty_specialty1_idx` ON `cpsc332_db_project`.`doctor_specialty` (`fk_spec_id` ASC) ;

SHOW WARNINGS;
CREATE INDEX `fk_doctor_has_specialty_doctor1_idx` ON `cpsc332_db_project`.`doctor_specialty` (`fk_doctor_id` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cpsc332_db_project`.`specialty_audit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cpsc332_db_project`.`specialty_audit` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cpsc332_db_project`.`specialty_audit` (
  `audit_id` INT NOT NULL,
  `doctor_name` VARCHAR(45) NULL,
  `action` ENUM("updated", "added") NULL,
  `specialty` VARCHAR(45) NULL,
  `date_of_modificaiton` DATETIME NULL,
  PRIMARY KEY (`audit_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cpsc332_db_project`.`appointment_test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cpsc332_db_project`.`appointment_test` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cpsc332_db_project`.`appointment_test` (
  `fk_test_id` INT NOT NULL,
  `fk_appointment_id` INT NOT NULL,
  PRIMARY KEY (`fk_test_id`, `fk_appointment_id`),
  CONSTRAINT `fk_appointment_has_test_test1`
    FOREIGN KEY (`fk_test_id`)
    REFERENCES `cpsc332_db_project`.`test` (`test_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appointment_test_appointment1`
    FOREIGN KEY (`fk_appointment_id`)
    REFERENCES `cpsc332_db_project`.`visit` (`visit_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_appointment_has_test_test1_idx` ON `cpsc332_db_project`.`appointment_test` (`fk_test_id` ASC) ;

SHOW WARNINGS;
CREATE INDEX `fk_appointment_test_appointment1_idx` ON `cpsc332_db_project`.`appointment_test` (`fk_appointment_id` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cpsc332_db_project`.`visit_prescription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cpsc332_db_project`.`visit_prescription` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cpsc332_db_project`.`visit_prescription` (
  `fk_visit_id` INT NOT NULL,
  `fk_prescription_id` INT NOT NULL,
  PRIMARY KEY (`fk_visit_id`, `fk_prescription_id`),
  CONSTRAINT `fk_medicine_has_appointment_medicine1`
    FOREIGN KEY (`fk_prescription_id`)
    REFERENCES `cpsc332_db_project`.`prescription` (`prescription_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicine_has_appointment_appointment1`
    FOREIGN KEY (`fk_visit_id`)
    REFERENCES `cpsc332_db_project`.`visit` (`visit_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_medicine_has_appointment_appointment1_idx` ON `cpsc332_db_project`.`visit_prescription` (`fk_visit_id` ASC) ;

SHOW WARNINGS;
CREATE INDEX `fk_medicine_has_appointment_medicine1_idx` ON `cpsc332_db_project`.`visit_prescription` (`fk_prescription_id` ASC) ;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
